spring.datasource.url=jdbc:postgresql://localhost:5432/moneypilotdatabase
spring.datasource.username=myuser
spring.datasource.password=mysecretpassword

management.endpoint.health.show-details=always
management.endpoint.web.exposure.include=health

jwt.secret=uma-string-bem-longa-para-dev-local-trocar-em-prod
jwt.expiration-ms=3600000